### ISSUE TITLE
Incompatible minify results with Rust 2021

### ISSUE THREAD

**Issue by mizar** [qryxip/rustminify#6]
example input:

```rust
pub fn miller_rabin(n: u64) -> bool {
    if n < 2 || n & 1 == 0 {
        return n == 2;
    }
    let mul = |a, b, n| -> u64 { ((a as u128) * (b as u128) % (n as u128)) as u64 };
    let pow = |mut b, mut p, n| -> u64 {
        if p == 0 {
            return (n > 1) as u64;
        }
        while p & 1 != 0 {
            p >>= 1;
            b = mul(b, b, n);
        }
        let mut r = b;
        p >>= 1;
        while p != 0 {
            b = mul(b, b, n);
            if p & 1 != 0 {
                r = mul(r, b, n);
            }
            p >>= 1;
        }
        r
    };
    let l = n - 1;
    let s = l.trailing_zeros();
    let d = l >> s;
    's: for &b in &[2, 325, 9375, 28178, 450775, 9780504, 1795265022] {
        let a = b % n;
        if a == 0 {
            continue;
        }
        let mut t = pow(a, d, n);
        if t == 1 || t == l {
            continue;
        }
        for _ in 1..s {
            t = mul(t, t, n);
            if t == l {
                continue 's;
            }
        }
        return false;
    }
    true
}
```

example output ( `rustminify < src/lib.rs` ):
```rust
pub fn miller_rabin(n:u64)->bool{if n<2||n&1==0{return n==2;}let mul=|a,b,n|->u64{((a as u128)*(b as u128)%(n as u128))as u64};let pow=|mut b,mut p,n|->u64{if p==0{return(n>1)as u64;}while p&1!=0{p>>=1;b=mul(b,b,n);}let mut r=b;p>>=1;while p!=0{b=mul(b,b,n);if p&1!=0{r=mul(r,b,n);}p>>=1;}r};let l=n-1;let s=l.trailing_zeros();let d=l>>s;'s:for&b in&[2,325,9375,28178,450775,9780504,1795265022]{let a=b%n;if a==0{continue;}let mut t=pow(a,d,n);if t==1||t==l{continue;}for _ in 1..s{t=mul(t,t,n);if t==l{continue's;}}return false;}true}
```

error messages:
```
error: prefix `continue` is unknown
 --> src/lib.rs:1:504
  |
1 | ...==1||t==l{continue;}for _ in 1..s{t=mul(t,t,n);if t==l{continue's;}}return false;}true}
  |                                                           ^^^^^^^^ unknown prefix
  |
  = note: prefixed identifiers and literals are reserved since Rust 2021
help: consider inserting whitespace here
```

https://doc.rust-lang.org/edition-guide/rust-2021/reserving-syntax.html
https://doc.rust-jp.rs/edition-guide/rust-2021/reserving-syntax.html
> - `any_identifier#`, `any_identifier"..."`, and `any_identifier'...'` are now reserved syntax, and no longer tokenize.
> - This is mostly relevant to macros. E.g. `quote!{ #a#b }` is no longer accepted.
> - It doesn't treat keywords specially, so e.g. `match"..." {}` is no longer accepted.
> - Insert whitespace between the identifier and the subsequent `#`, `"`, or `'` to avoid errors.
> - Edition migrations will help you insert whitespace in such cases.
> 
> ---
> 
> - `shikibetsushi#`, `shikibetsushi"..."`, `shikibetsushi'...'` の3つの構文が新たに予約され、トークン分割されなくなりました。
> - 主に影響を受けるのはマクロです。例えば、`quote!{ #a#b }` と書くことはできなくなりました。
> - キーワードが特別扱いされることもないので、例えば `match"..." {}` と書くこともできなくなりました。
> - 識別子と後続の `#`, `"`, `'` の間に空白文字を挿入することで、エラーを回避できます。
> - エディション移行ツールは、必要な場所に空白を挿入してくれます。

**Comment by mizar** [comment]
https://doc.rust-lang.org/reference/tokens.html#reserved-prefixes
> **Edition Differences**: Starting with the 2021 edition, reserved prefixes are reported as an error by the lexer (in particular, they cannot be passed to macros).
>
> Before the 2021 edition, reserved prefixes are accepted by the lexer and interpreted as multiple tokens (for example, one token for the identifier or keyword, followed by a `#` token).
>
> Examples accepted in all editions:
> ```rust
> macro_rules! lexes {($($_:tt)*) => {}}
> lexes!{a #foo}
> lexes!{continue 'foo}
> lexes!{match "..." {}}
> lexes!{r#let#foo}         // three tokens: r#let # foo
> ```
>
> Examples accepted before the 2021 edition but rejected later:
> ```rust,edition2018
> macro_rules! lexes {($($_:tt)*) => {}}
> lexes!{a#foo}
> lexes!{continue'foo}
> lexes!{match"..." {}}
> ```

**Comment by qryxip** [comment]
Should be resolved by #7.
